// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Text field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Experience field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.experience
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  experience: prismic.RichTextField;

  /**
   * Work Experience field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.work_experience
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  work_experience: prismic.RichTextField;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Item in *Blog → Article Technologies*
 */
export interface BlogDocumentDataArticleTechnologiesItem {
  /**
   * Article Tech field in *Blog → Article Technologies*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.article_technologies[].article_tech
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  article_tech: prismic.SelectField<
    | "Javascript"
    | "Swift"
    | "WebGL"
    | "WebGPU"
    | "Metal"
    | "HTML"
    | "CSS"
    | "SVG"
    | "Three.js"
    | "React"
  >;
}

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Article Technologies field in *Blog*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.article_technologies[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  article_technologies: prismic.GroupField<
    Simplify<BlogDocumentDataArticleTechnologiesItem>
  >;

  /**
   * Table of Contents field in *Blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.table_of_contents
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  table_of_contents: prismic.RichTextField;

  /**
   * External Resource Name field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.external_resource_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  external_resource_name: prismic.KeyTextField;

  /**
   * External Link field in *Blog*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.external_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  external_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * SEO Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  seo_description: prismic.KeyTextField;

  /**
   * title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * year field in *Blog*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  year: prismic.NumberField;

  /**
   * body field in *Blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

/**
 * Item in *CV → work*
 */
export interface CvDocumentDataWorkItem {
  /**
   * work-entry field in *CV → work*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cv.work[].work-entry
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  "work-entry": prismic.RichTextField;
}

/**
 * Content for CV documents
 */
interface CvDocumentData {
  /**
   * intro field in *CV*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cv.intro-web
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  "intro-web": prismic.RichTextField;

  /**
   * print-intro field in *CV*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cv.intro-print
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  "intro-print": prismic.RichTextField;

  /**
   * programming field in *CV*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cv.programming
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  programming: prismic.RichTextField;

  /**
   * web field in *CV*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cv.web
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  web: prismic.RichTextField;

  /**
   * ios field in *CV*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cv.ios
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  ios: prismic.RichTextField;

  /**
   * computer graphics field in *CV*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cv.computer_graphics
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  computer_graphics: prismic.RichTextField;

  /**
   * backend field in *CV*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cv.backend
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  backend: prismic.RichTextField;

  /**
   * languages field in *CV*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cv.languages
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  languages: prismic.RichTextField;

  /**
   * software field in *CV*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cv.software
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  software: prismic.RichTextField;

  /**
   * hobbies field in *CV*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cv.hobbies
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hobbies: prismic.RichTextField;

  /**
   * work field in *CV*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cv.work[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  work: prismic.GroupField<Simplify<CvDocumentDataWorkItem>>;

  /**
   * education field in *CV*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cv.education
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  education: prismic.RichTextField;
}

/**
 * CV document from Prismic
 *
 * - **API ID**: `cv`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CvDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<CvDocumentData>, "cv", Lang>;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Intro Text field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.intro_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro_text: prismic.RichTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for pdf-cv documents
 */
interface PdfCvDocumentData {
  /**
   * pdf field in *pdf-cv*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: pdf-cv.pdf
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  pdf: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * pdf-cv document from Prismic
 *
 * - **API ID**: `pdf-cv`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PdfCvDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PdfCvDocumentData>,
    "pdf-cv",
    Lang
  >;

/**
 * Item in *speaking → Project Technologies*
 */
export interface SpeakingDocumentDataProjectTechnologiesItem {
  /**
   * Technology field in *speaking → Project Technologies*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: speaking.project_technologies[].technology
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  technology: prismic.SelectField<
    "Javascript" | "Swift" | "WebGL" | "Metal" | "HTML" | "CSS" | "SVG"
  >;
}

/**
 * Content for speaking documents
 */
interface SpeakingDocumentData {
  /**
   * SEO description field in *speaking*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speaking.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  seo_description: prismic.KeyTextField;

  /**
   * Project Title field in *speaking*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speaking.project_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_title: prismic.KeyTextField;

  /**
   * Project Technologies field in *speaking*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: speaking.project_technologies[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  project_technologies: prismic.GroupField<
    Simplify<SpeakingDocumentDataProjectTechnologiesItem>
  >;

  /**
   * Project Type field in *speaking*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: speaking.project_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  project_type: prismic.SelectField<"Video Course" | "Presentation">;

  /**
   * Project Year field in *speaking*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: speaking.project_year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  project_year: prismic.NumberField;

  /**
   * project link field in *speaking*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: speaking.project_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  project_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * project tech field in *speaking*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speaking.project_tech
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_tech: prismic.RichTextField;

  /**
   * Project Image field in *speaking*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: speaking.project_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  project_image: prismic.ImageField<never>;

  /**
   * Project Body field in *speaking*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speaking.project_body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_body: prismic.RichTextField;
}

/**
 * speaking document from Prismic
 *
 * - **API ID**: `speaking`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SpeakingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SpeakingDocumentData>,
    "speaking",
    Lang
  >;

/**
 * Item in *work → Project Technologies*
 */
export interface WorkDocumentDataProjectTechnologiesListItem {
  /**
   * Project Tech field in *work → Project Technologies*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: work.project_technologies_list[].project_tech
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  project_tech: prismic.SelectField<
    | "Javascript"
    | "Swift"
    | "C"
    | "C++"
    | "WebAssembly"
    | "WebGL"
    | "WebGPU"
    | "Metal"
    | "HTML"
    | "CSS"
    | "SVG"
    | "Wordpress"
    | "Drupal"
    | "SwiftUI"
    | "ARKit"
    | "Three.js"
    | "VR"
    | "React"
    | "Express.js"
    | "canvas2d"
  >;
}

/**
 * Content for work documents
 */
interface WorkDocumentData {
  /**
   * Project Title field in *work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.project_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_title: prismic.KeyTextField;

  /**
   * Project Type field in *work*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: work.project_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  project_type: prismic.SelectField<
    | "Graphics Demo"
    | "Native Application"
    | "Website"
    | "Game"
    | "Visualisation"
    | "Animation"
  >;

  /**
   * Project Year field in *work*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: work.project_year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  project_year: prismic.NumberField;

  /**
   * Project Technologies field in *work*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work.project_technologies_list[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  project_technologies_list: prismic.GroupField<
    Simplify<WorkDocumentDataProjectTechnologiesListItem>
  >;

  /**
   * Project Image field in *work*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work.project_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  project_image: prismic.ImageField<never>;

  /**
   * Project Main Link field in *work*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: work.project_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  project_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Project Secondary Link field in *work*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: work.project_secondary_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  project_secondary_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Project Body field in *work*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.project_body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_body: prismic.RichTextField; /**
   * Meta Title field in *work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.meta_title
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.meta_description
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * meta_image field in *work*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work.meta_image
   * - **Tab**: Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * work document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<WorkDocumentData>, "work", Lang>;

export type AllDocumentTypes =
  | AboutDocument
  | BlogDocument
  | CvDocument
  | HomeDocument
  | PdfCvDocument
  | SpeakingDocument
  | WorkDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataArticleTechnologiesItem,
      CvDocument,
      CvDocumentData,
      CvDocumentDataWorkItem,
      HomeDocument,
      HomeDocumentData,
      PdfCvDocument,
      PdfCvDocumentData,
      SpeakingDocument,
      SpeakingDocumentData,
      SpeakingDocumentDataProjectTechnologiesItem,
      WorkDocument,
      WorkDocumentData,
      WorkDocumentDataProjectTechnologiesListItem,
      AllDocumentTypes,
    };
  }
}
